### PR TITLE
Add type hints to be compatible with symfony/serializer on PHP8.1+

### LINKED ISSUE #9: Broken against latest symfony/serializer
Tried adding this package to a Laravel-10 project running on PHP-8.3 and immediately got this:

```
PHP Fatal error:  Declaration of ShipStream\Ups\Api\Normalizer\JaneObjectNormalizer::denormalize($data, $class, $format = null, array $context = []) must be compatible with Symfony\Component\Serializer\Normalizer\DenormalizerInterface::denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed in /path/to/my/vendor/shipstream/ups-rest-php-sdk/src/Api/Normalizer/JaneObjectNormalizer.php on line 40
```

I saw you recently dropped your explicit composer dependency on `symfony/serializer` "to allow installing on PHP 8.x", but I don't think it is that simple. If your code is not compatible with the latest versions of `symfony/serializer` you should declare the maximum version you are compatible with. Otherwise you should make your code that extends/implements these interfaces compatible with the latest.

### PR DESCRIPTION
**Pull request by staticglobal**
Fixes #9

`composer test` passes cleanly against Laravel-10 on PHP-8.3 with these changes

### CODE REVIEW

**Comment by staticglobal** [comment]
lol look how naive I was an hour ago when I opened this PR. Yes these changes were enough to get the unit tests to pass and my code to instantiate a new Client, but the same issue is present in *all* the files under `Api/Normalizer`. Since these files are generated by Jane anyway, probably best to just re-generate everything instead of hand-edit.

**Comment by staticglobal** [comment]
OK I didn't have docker readily available to me on the remote host I am working on, so was unable to run `generate.sh`.

HOWEVER, I *was* able to apply the necessary syntax changes to all the files in `Api/Normalizer` using this `sed` command:
```
sed -i -e 's#public function denormalize($data, $class, $format = null, array $context = array())#public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed#' \
    -e 's#public function normalize($object, $format = null, array $context = array())#public function normalize(mixed $object, ?string $format = null, array $context = []): \\ArrayObject|array|string|int|float|bool|null#' \
    -e 's#array()#[]#' \
    *.php
```

I am going to push a commit with the results, as that seems to be working fine for me to be productive in my project. Though I fully understand if you would prefer to use Jane to regenerate these files and decline this PR.

**Comment by staticglobal** [comment]
...and then this command has to be run to hit all the files under `src/Normalizer/` ☹️ 

```
sed -i -e 's#public function denormalize($data, $class, $format = null, array $context = \[\])#public function denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed#' \
    -e 's#return parent::denormalize($data, $class,#return parent::denormalize($data, $type,#' \
    *.php */*.php
```

**Comment by elidrissidev** [comment]
Hi, thanks for your contribution.

I've just released version 2.0 which should be compatible with Symfony 6 and 7, there were differences in interfaces between the two versions, but Jane handles that now. Thanks!

**Pull request closed without merging**
